#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Feb  7 20:41:16 2020

@author: Mehmet Eyüpoğlu
"""

import random
s = "abcdefghijklmnopqrstuvwxyz01234567890ABCDEFGHIJKLMNOPQRSTUVWXYZ!@#$%^&*()?"
passlen = int(input('Enter the length of your password:  '))
password = ''.join(random.sample(s, passlen))

print('Your password is: {} '.format(password)) 